type: 'UNIFORM'
parameters:
    hidden_layer_size: 128
    batch_size: 128
    discount: 0.99
    replay_capacity: 100000
    min_replay_size: 2048
    sgd_period: 1
    target_soft_update: 0.005
    lr_Q: 0.001
    epsilon_0: 10
    exploration_prob: 0.2