defaults:
  - agent: gvf_explorer
  - environment: narms
  - _self_

experiment:
  num_simulations: 30
  num_processes: 30
  horizon: 1000000 #500k
  frequency_evaluation: 500 #250
  delta: 0.01
  epsilon: 0.1
  discount_factor: 0.9
  solver_type: 'GUROBI'
  reward_set: 'RewardFree'
  single_policy: False

