defaults:
  - agent: mr_nas_pe
  - environment: narms
  - _self_

experiment:
  num_simulations: 30
  num_processes: 15
  horizon: 300000
  frequency_evaluation: 250
  delta: 0.01
  epsilon: 0.1
  discount_factor: 0.99
  solver_type: 'GUROBI'
